FROM python:3.11-slim

WORKDIR /app

COPY proto/ ./proto/
COPY satellites/ ./satellites/

RUN pip install --no-cache-dir fastapi uvicorn grpcio grpcio-tools httpx

ENV SAT_ID=SAT-01
ENV GRPC_PORT=5001
ENV P2P_PORT=6001
ENV REGISTRY_URL=http://mission-control:8000

CMD ["sh", "-c", "python satellites/satellite_node.py --id ${SAT_ID} --grpc-port ${GRPC_PORT} --p2p-port ${P2P_PORT} --registry ${REGISTRY_URL}"]
