# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import satellite_pb2 as proto_dot_satellite__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/satellite_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SatelliteServiceStub:
    """gRPC Satellite Service contract
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/satellite.SatelliteService/GetHealth',
                request_serializer=proto_dot_satellite__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetTelemetry = channel.unary_unary(
                '/satellite.SatelliteService/GetTelemetry',
                request_serializer=proto_dot_satellite__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.TelemetryResponse.FromString,
                _registered_method=True)
        self.GetSatelliteInfo = channel.unary_unary(
                '/satellite.SatelliteService/GetSatelliteInfo',
                request_serializer=proto_dot_satellite__pb2.InfoRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/satellite.SatelliteService/Ping',
                request_serializer=proto_dot_satellite__pb2.PingRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.PingResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/satellite.SatelliteService/ExecuteCommand',
                request_serializer=proto_dot_satellite__pb2.CommandRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendP2PMessage = channel.unary_unary(
                '/satellite.SatelliteService/SendP2PMessage',
                request_serializer=proto_dot_satellite__pb2.P2PRequest.SerializeToString,
                response_deserializer=proto_dot_satellite__pb2.P2PResponse.FromString,
                _registered_method=True)


class SatelliteServiceServicer:
    """gRPC Satellite Service contract
    """

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSatelliteInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendP2PMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SatelliteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=proto_dot_satellite__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.HealthResponse.SerializeToString,
            ),
            'GetTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTelemetry,
                    request_deserializer=proto_dot_satellite__pb2.TelemetryRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.TelemetryResponse.SerializeToString,
            ),
            'GetSatelliteInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSatelliteInfo,
                    request_deserializer=proto_dot_satellite__pb2.InfoRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.InfoResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=proto_dot_satellite__pb2.PingRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.PingResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=proto_dot_satellite__pb2.CommandRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.CommandResponse.SerializeToString,
            ),
            'SendP2PMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendP2PMessage,
                    request_deserializer=proto_dot_satellite__pb2.P2PRequest.FromString,
                    response_serializer=proto_dot_satellite__pb2.P2PResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'satellite.SatelliteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('satellite.SatelliteService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SatelliteService:
    """gRPC Satellite Service contract
    """

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/GetHealth',
            proto_dot_satellite__pb2.HealthRequest.SerializeToString,
            proto_dot_satellite__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/GetTelemetry',
            proto_dot_satellite__pb2.TelemetryRequest.SerializeToString,
            proto_dot_satellite__pb2.TelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSatelliteInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/GetSatelliteInfo',
            proto_dot_satellite__pb2.InfoRequest.SerializeToString,
            proto_dot_satellite__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/Ping',
            proto_dot_satellite__pb2.PingRequest.SerializeToString,
            proto_dot_satellite__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/ExecuteCommand',
            proto_dot_satellite__pb2.CommandRequest.SerializeToString,
            proto_dot_satellite__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendP2PMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/satellite.SatelliteService/SendP2PMessage',
            proto_dot_satellite__pb2.P2PRequest.SerializeToString,
            proto_dot_satellite__pb2.P2PResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
